# Generated by Django 5.1.4 on 2025-03-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Client/admin', 'verbose_name_plural': 'Clients/admin'},
        ),
    ]
