# Generated by Django 5.1.4 on 2025-03-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DemandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='demandes/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDÉ', 'Validé'), ('REFUSÉ', 'Refusé')], default='EN_ATTENTE', max_length=12)),
            ],
            options={
                'verbose_name': 'DemandeService',
                'verbose_name_plural': 'DemandeServices',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='devis/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDÉ', 'Validé'), ('REFUSÉ', 'Refusé')], default='EN_ATTENTE', max_length=12)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée')], default='IMPAYEE', max_length=10)),
                ('invoice_type', models.CharField(choices=[('R', 'RECEIPT'), ('P', 'PROFORMA INVOICE'), ('I', 'INVOICE')], max_length=1)),
                ('mode_paiement', models.CharField(choices=[('CB', 'Carte Bancaire'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], default='CB', max_length=50)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date_creation', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_creation'],
            },
        ),
    ]
