# Generated by Django 5.1.4 on 2025-03-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='taxe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'RECEIPT'), ('P', 'PROFORMA INVOICE'), ('I', 'INVOICE')], max_length=15),
        ),
    ]
