# Generated by Django 5.1.4 on 2025-03-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='duree',
            field=models.IntegerField(default=10, help_text='en jours'),
        ),
    ]
