# Generated by Django 5.1.4 on 2025-03-22 14:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Service', '0003_devis_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='taxe',
        ),
        migrations.AddField(
            model_name='facture',
            name='quantite',
            field=models.IntegerField(default=10, help_text='en jours'),
        ),
        migrations.AddField(
            model_name='facture',
            name='validite',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/devis'), upload_to='devis/'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='validite',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='invoice_type',
            field=models.CharField(default='FACTURE', help_text='type_document', max_length=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=10),
        ),
    ]
