# Generated by Django 5.1.4 on 2025-03-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Service', '0003_facture_fichier_pdf_facture_numero_facture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du sous-service')),
            ],
        ),
        migrations.RemoveField(
            model_name='demandeservice',
            name='fichier',
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total'),
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Service.service')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Service.subservice')),
            ],
            options={
                'unique_together': {('service', 'sub_service')},
            },
        ),
        migrations.CreateModel(
            name='SelectedSubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Service.demandeservice')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Service.subservice')),
            ],
            options={
                'unique_together': {('service_request', 'sub_service')},
            },
        ),
        migrations.AddField(
            model_name='demandeservice',
            name='sub_services',
            field=models.ManyToManyField(related_name='service_requests', through='Gestion_Service.SelectedSubService', to='Gestion_Service.subservice'),
        ),
        migrations.AddField(
            model_name='service',
            name='sub_services',
            field=models.ManyToManyField(related_name='services', through='Gestion_Service.ServicePricing', to='Gestion_Service.subservice'),
        ),
    ]
