# Generated by Django 5.1.4 on 2025-03-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Service', '0004_subservice_remove_demandeservice_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeservice',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='demandes/'),
        ),
    ]
