# Generated by Django 5.1.4 on 2025-03-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Service', '0004_remove_facture_mode_paiement_remove_facture_montant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeservice',
            name='montant',
        ),
        migrations.AlterField(
            model_name='demandeservice',
            name='statut',
            field=models.CharField(default='EN_ATTENTE', max_length=12),
        ),
    ]
