# Generated by Django 5.1.4 on 2025-03-26 10:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Service', '0006_alter_demandeservice_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='devis/'),
        ),
    ]
